#!/bin/bash -e

if [ ! -x "src/latte-jvm" ]; then
    echo ERROR 1>&2
    echo "Please run \`make' first"
    exit 1
fi

if [ -z "$(echo $1 | grep '\.lat$')" ]; then
    echo ERROR 1>&2
    echo "Please provide *.lat file to compile"
    exit 1
fi

src/latte-jvm "$1"
JASMIN_INPUT=$(echo "$1" | sed -e 's/\.lat$/.j/')
java -jar lib/jasmin.jar "$JASMIN_INPUT"

